### ISSUE TITLE
Doesn't work behind a proxy

### ISSUE THREAD

**Issue by mtitolo** [segiddins/beta-pod#1]
I've tried a number of proxy settings (including ssh proxy) and this just won't work with any combination.

```
$ beta-pod seg-infer-umbrella-header install
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Operation timed out - connect(2) (Errno::ETIMEDOUT)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
    from /Users/michele/.gem/gems/beta-pod-1.1.1/exe/beta-pod:10:in `sha_for_ref'
    from /Users/michele/.gem/gems/beta-pod-1.1.1/exe/beta-pod:57:in `<top (required)>'
    from /Users/michele/.gem/bin/beta-pod:23:in `load'
    from /Users/michele/.gem/bin/beta-pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Ummm... Maybe open-uri doesn't do the right think regarding proxies?

**Comment by mtitolo** [comment]
All of the docs say open needs to pass in proxy information. If the variables are set in the shell, this should be pretty easy to do.

**Comment by mtitolo** [comment]
Hmm might be a ruby bug. http://stackoverflow.com/questions/20994460/ruby-2-0-open-uri-always-uses-proxy-even-with-proxy-nil-flag

I'll try in a newer ruby.

**Comment by mtitolo** [comment]
:sob: Nope this is not a problem in an older ruby

**Comment by segiddins** [comment]
I'm open to hacking open URI to make it work, but I dont have a proxy I can debug with 😔
